[package]
name = "native-launcher"
version = "0.1.0"
edition = "2021"
workspace = "../.."

[dependencies]
bevy-starfighter = { package = "bevy-starfighter", path = "../.." }
bevy = { version = "0.19", default-features = false }
clap = { version = "3.1.7", features = ["derive"] }
tracing = "0.1"

[profile.release]
debug = true
